name: 🚀 Deploy MentorBooster to Prod EC2

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'What change is going live in this deployment?'
        required: true
        default: 'Bug fix, UI update, or performance improvement'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        continue-on-error: false

      - name: ☕ Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        continue-on-error: false

      - name: 🏗️ Build with Maven (skip tests)
        run: |
          echo "🛠️ Starting Maven build..."
          # ⚠️ IMPORTANT:
          # If you use './mvnw clean package', make sure your project and repo includes:
          # ✅ mvnw
          # ✅ mvnw.cmd
          # ✅ .mvn/wrapper/
          #
          # Otherwise, GitHub Actions won't know how to run Maven and this step will fail!
          chmod +x mvnw 
          ./mvnw clean package -DskipTests
          echo "✅ Build complete!"
        continue-on-error: false

      - name: 📦 Copy JAR to Prod EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_PROD_USER }}
          key: ${{ secrets.EC2_PROD_SSH_KEY }}
          source: "target/*.jar"
          target: "~/mentorbooster-deploy"
          strip_components: 1
        continue-on-error: false

      - name: 🏷️ Rename JAR with IST timestamp and update symlink
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_PROD_USER }}
          key: ${{ secrets.EC2_PROD_SSH_KEY }}
          script: |
            echo "🔍 Navigating to deploy directory..."
            cd ~/mentorbooster-deploy
            
            echo "🔍 Searching for latest .jar file..."
            latest_file=$(ls -t *.jar 2>/dev/null | head -n 1)
            
            if [ -z "$latest_file" ]; then
              echo "❌ No .jar files found. Exiting..."
              exit 1
            fi
            
            echo "✅ Found: $latest_file"
            
            timestamp=$(TZ='Asia/Kolkata' date +"%Y-%m-%d-%H-%M-%S")
            echo "🕒 IST Timestamp: $timestamp"
            
            new_name="mentorbooster-${timestamp}.jar"
            echo "📦 Renaming '$latest_file' → '$new_name'"
            mv "$latest_file" "$new_name"
            
            echo "🔗 Updating symlink 'mentorbooster-latest.jar' → '$new_name'"
            ln -sf "$new_name" mentorbooster-latest.jar
            
            echo "✅ Rename and symlink update complete!"
        continue-on-error: false

      - name: 🔁 Restart MentorBooster app on Prod EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_PROD_USER }}
          key: ${{ secrets.EC2_PROD_SSH_KEY }}
          script: |
            echo "🧠 Navigating to deploy directory..."
            cd ~/mentorbooster-deploy
            
            echo "🧹 Restarting app using start.sh"
            ./start.sh
            
            echo "🚀 App restarted! Check log.txt for logs."
        continue-on-error: false
